const TODO = {
  TODO_ALL_REQUST: "TODO_ALL_REQUST",
  TODO_ALL_SUCCESS: "TODO_ALL_SUCCESS",
  TODO_ALL_FAIL: "TODO_ALL_FAIL",
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  MARK_TODO_DONE: "MARK_TODO_DONE",
  INITIAL_STATE: "INITIAL_STATE",
};

export default TODO;
