const TODO = {
  TODO_ALL_REQUST: "TODO_ALL_REQUST",
  TODO_ALL_SUCCESS: "TODO_ALL_SUCCESS",
  TODO_ALL_FAIL: "TODO_ALL_FAIL",

  TODO_ADD_REQUEST: "TODO_ADD_REQUEST",
  TODO_ADD_SUCESS: "TODO_ADD_SUCESS",
  TODO_ADD_FAIL: "TODO_ADD_FAIL",

  TODO_DELETE_REQUEST: "TODO_DELETE_REQUEST",
  TODO_DELETE_SUCESS: "TODO_DELETE_SUCESS",
  TODO_DELETE_FAIL: "TODO_DELETE_FAIL",

  INITIAL_STATE: "INITIAL_STATE",
};

export default TODO;
